version: '3.7'

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn --workers=3 farmbox.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8080:8000
    env_file: .env
  # nginx:
  #   image: "${NGINX_IMAGE}"
  #   volumes:
  #     - static_volume:/usr/src/app/staticfiles
  #     - media_volume:/usr/src/app/mediafiles
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web

volumes:
  static_volume:
  media_volume:
