version: '3.7'

services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn farmbox.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
    # networks:
    #   - farmbox
volumes:
  static_volume:
  media_volume:

# networks:
#   farmbox:
#     driver: bridge
