version: '3.7'

services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn farmbox.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    # expose:
    #   - 8000
    env_file:
      - ./.env.prod
    networks:
      - farmbox

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   volumes:
  #     - /staticfiles:/home/app/web/staticfiles
  #   depends_on:
  #     - web
  #   networks:
  #     - farmbox
# volumes:
  # static_volume:
  # media_volume:

networks:
  farmbox:
    driver: bridge
