# Generated by Django 3.0.5 on 2020-10-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=512, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=512, verbose_name="Last Name"),
                ),
                ("address", models.CharField(max_length=512, verbose_name="Address")),
                ("postcode", models.CharField(max_length=8, verbose_name="Postcode")),
                ("email", models.EmailField(max_length=64, verbose_name="Email")),
                ("phone", models.CharField(max_length=64, verbose_name="Phone")),
                ("notes", models.TextField(blank=True, verbose_name="Customer Notes")),
            ],
        ),
    ]
