# Generated by Django 3.0.5 on 2020-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
