# Generated by Django 3.0.5 on 2020-04-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_fixtures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sequence',)},
        ),
    ]
