# Generated by Django 3.0.5 on 2020-04-05 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=512)),
                ('customer_address', models.CharField(max_length=512)),
                ('customer_postcode', models.CharField(max_length=8)),
                ('customer_email', models.EmailField(max_length=64)),
                ('customer_phone', models.CharField(max_length=64)),
                ('fulfillment_method', models.CharField(choices=[('Delivery', 'Delivery'), ('Collection', 'Collection')], max_length=16)),
                ('collection_location', models.CharField(blank='N/A', choices=[('Denbies', 'Denbies'), ('Ockley', 'Ockley')], max_length=16)),
                ('customer_specified_fulfilled_at', models.DateTimeField()),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
