# Generated by Django 3.0.5 on 2020-04-13 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=512, verbose_name='Name')),
                ('customer_address', models.CharField(max_length=512, verbose_name='Address')),
                ('customer_postcode', models.CharField(max_length=8, verbose_name='Postcode')),
                ('customer_email', models.EmailField(max_length=64, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=64, verbose_name='Phone')),
                ('fulfillment_method', models.CharField(choices=[('Delivery', 'Delivery'), ('Collection', 'Collection')], max_length=16, verbose_name='DELIVERY / COLLECTION')),
                ('collection_location', models.CharField(blank='N/A', choices=[('Denbies', 'Denbies'), ('Ockley', 'Ockley')], max_length=16, verbose_name='If collection, which shop?')),
                ('notes', models.TextField(blank=True, verbose_name='NOTES')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('fulfillment_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.FulfillmentEvent')),
                ('products', models.ManyToManyField(to='product.Product')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
