# Generated by Django 3.0.5 on 2020-05-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_create_sample_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Collect from Ockley Shop', 'Collection Ockley'), ('Collect from Denbies Shop', 'Collection Denbies')], max_length=30, verbose_name='Fulfillment Method'),
        ),
    ]
