# Generated by Django 3.0.5 on 2020-04-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_create_sample_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField()),
                ('fulfillment_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.FulfillmentEvent')),
                ('order_created', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Order Succesfully Created?')),
            ],
        ),
    ]
