# Generated by Django 3.0.5 on 2020-06-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200526_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='repeated_order_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
