# Generated by Django 3.0.5 on 2020-05-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200512_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['f_number']},
        ),
    ]
