# Generated by Django 3.0.5 on 2020-10-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_order_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(db_index=True, max_length=64, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_postcode",
            field=models.CharField(
                db_index=True, max_length=8, verbose_name="Postcode"
            ),
        ),
    ]
