# Generated by Django 3.0.5 on 2020-10-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_auto_20200626_0555"),
        ("order", "0008_create_customers_from_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("integration_id", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.CreateModel(
            name="ProductSelection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_selections",
                        to="product.Product",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.OrderTemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordertemplate",
            name="products",
            field=models.ManyToManyField(
                related_name="products",
                through="order.ProductSelection",
                to="product.Product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.OrderTemplate",
            ),
        ),
    ]
